package com.fernanortega.rickandmorty.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF466730)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFC7EEA9)
val onPrimaryContainerLight = Color(0xFF0A2100)
val secondaryLight = Color(0xFF56624B)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFD9E7CA)
val onSecondaryContainerLight = Color(0xFF141E0C)
val tertiaryLight = Color(0xFF386665)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFBBECEB)
val onTertiaryContainerLight = Color(0xFF002020)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFF8FAF0)
val onBackgroundLight = Color(0xFF191D16)
val surfaceLight = Color(0xFFF8FAF0)
val onSurfaceLight = Color(0xFF191D16)
val surfaceVariantLight = Color(0xFFE0E4D6)
val onSurfaceVariantLight = Color(0xFF43483E)
val outlineLight = Color(0xFF74796D)
val outlineVariantLight = Color(0xFFC4C8BB)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2E312A)
val inverseOnSurfaceLight = Color(0xFFF0F2E7)
val inversePrimaryLight = Color(0xFFACD28F)
val surfaceDimLight = Color(0xFFD9DBD1)
val surfaceBrightLight = Color(0xFFF8FAF0)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF3F5EA)
val surfaceContainerLight = Color(0xFFEDEFE4)
val surfaceContainerHighLight = Color(0xFFE7E9DF)
val surfaceContainerHighestLight = Color(0xFFE1E4D9)


val primaryDark = Color(0xFFACD28F)
val onPrimaryDark = Color(0xFF193705)
val primaryContainerDark = Color(0xFF2F4F1B)
val onPrimaryContainerDark = Color(0xFFC7EEA9)
val secondaryDark = Color(0xFFBDCBAF)
val onSecondaryDark = Color(0xFF283420)
val secondaryContainerDark = Color(0xFF3E4A35)
val onSecondaryContainerDark = Color(0xFFD9E7CA)
val tertiaryDark = Color(0xFFA0CFCE)
val onTertiaryDark = Color(0xFF003737)
val tertiaryContainerDark = Color(0xFF1E4E4E)
val onTertiaryContainerDark = Color(0xFFBBECEB)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF11140E)
val onBackgroundDark = Color(0xFFE1E4D9)
val surfaceDark = Color(0xFF11140E)
val onSurfaceDark = Color(0xFFE1E4D9)
val surfaceVariantDark = Color(0xFF43483E)
val onSurfaceVariantDark = Color(0xFFC4C8BB)
val outlineDark = Color(0xFF8E9286)
val outlineVariantDark = Color(0xFF43483E)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE1E4D9)
val inverseOnSurfaceDark = Color(0xFF2E312A)
val inversePrimaryDark = Color(0xFF466730)
val surfaceDimDark = Color(0xFF11140E)
val surfaceBrightDark = Color(0xFF373A33)
val surfaceContainerLowestDark = Color(0xFF0C0F09)
val surfaceContainerLowDark = Color(0xFF191D16)
val surfaceContainerDark = Color(0xFF1D211A)
val surfaceContainerHighDark = Color(0xFF282B24)
val surfaceContainerHighestDark = Color(0xFF33362F)








